version: '3.9'

services:
    activej:
        image: maven:eclipse-temurin
        working_dir: /root/app
        entrypoint: bash -c "if ! command -v deno &> /dev/null ; then apt update && apt install unzip && curl -fsSL https://deno.land/x/install/install.sh | sh; fi && if ! command -v denon &> /dev/null ; then deno install -qAf --unstable https://deno.land/x/denon/denon.ts; fi && denon start"
        tty: true
        volumes:
            - .:/root/app
            - deno:/root/.deno
            - m2:/root/.m2
            - maven-home:/usr/share/maven
        tmpfs:
            - /root/app/target
        ports:
            - 8080:8080
        restart: unless-stopped
        environment:
            - PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.deno/bin

volumes:
    maven-home:
    m2:
    deno: